// examples/svelte-inertia-jinja/resources/pages/Home.svelte
<script lang="ts">
  import { Link } from "@inertiajs/svelte"

  let { message }: { message?: string } = $props()
</script>

<svelte:head>
  <title>Home - svelte-inertia-jinja</title>
</svelte:head>

<main class="mx-auto max-w-5xl space-y-6 px-4 py-10">
  <header class="space-y-2">
    <p class="font-semibold text-[#edb641] text-sm uppercase tracking-[0.14em]">Litestar · Vite</p>
    <h1 class="font-semibold text-3xl text-[#202235]">Library (Svelte 5 + Inertia + Jinja)</h1>
    <p class="max-w-3xl text-slate-600">
      Template mode: a Jinja2 shell wraps the Inertia bootstrap. Page payloads are injected into the
      <code>#app_page</code> script element by the server.
    </p>
    {#if message}
      <p class="font-medium text-[#202235]">{message}</p>
    {/if}
  </header>

  <nav class="flex gap-4">
    <Link
      href="/books"
      class="rounded-full bg-[#202235] px-6 py-2 font-semibold text-sm text-white transition hover:bg-[#2d3348]"
    >
      View Books
    </Link>
  </nav>
</main>

// examples/vue-inertia-jinja/resources/pages/Home.vue
<script setup lang="ts">
import { Head, Link } from "@inertiajs/vue3"

defineProps<{
  message?: string
}>()
</script>

<template>
  <Head title="Home" />
  <div class="max-w-5xl mx-auto px-4 py-10 space-y-6">
    <div class="space-y-3">
      <p class="uppercase tracking-[0.14em] text-sm font-semibold text-[#edb641]">Litestar · Vite</p>
      <h1 class="text-3xl font-semibold text-[#202235]">Library (Vue + Inertia Jinja)</h1>
      <p class="text-slate-600">Server-driven SPA example with Jinja2 template mode.</p>
      <p v-if="message" class="text-[#202235] font-medium">{{ message }}</p>
    </div>

    <nav class="flex gap-4">
      <Link href="/books" class="rounded-full bg-[#202235] px-6 py-2 font-semibold text-white text-sm transition hover:bg-[#2d3348]">
        View Books
      </Link>
    </nav>
  </div>
</template>
